export const RUNTIME_STREAM_PROTOCOL_VERSION = 1;
export const RUNTIME_STREAM_PROTOCOL_MIN_SUPPORTED_VERSION = 1;
export const RUNTIME_STREAM_PROTOCOL_MAX_SUPPORTED_VERSION = 2;
export const RUNTIME_CONTROL_PROTOCOL_VERSION = 1;
